== Basic Branch Build Strategies Plugin

This plugin provides some basic branch build strategies for use with http://wiki.jenkins.io/display/JENKINS/Branch+API+Plugin[Branch API] based projects.

For generic information about how to use the Basic Branch Build Strategies plugin, please see link:docs/user{outfilesuffix}[the user guide]

For other details on the plugin see http://wiki.jenkins.io/display/JENKINS/Basic+Branch+Build+Strategies+Plugin[the wiki page]

For changes to the plugin see link:CHANGES{outfilesuffix}[the changelog]

=== Developer information

The following information is provided for anyone wanting to develop this plugin.

* link:CONTRIBUTING{outfilesuffix}[Contributor guidelines]

==== Environment

The following build environment is required to build this plugin

* `java-1.8` and `maven-3.5.2`

==== Build

To build the plugin locally:

[source,shell]
----
mvn clean verify
----

==== Release

To release the plugin:

[source,shell]
----
mvn release:prepare release:perform -B
----

==== Test local instance

To test in a local Jenkins instance

[source,shell]
----
mvn hpi:run
----
